Add methods to create, update, and delete secrets
thycotic/tss-sdk-go pull request #12
Opened 2022-01-04 19:15 UTC by chaserb

This PR addresses #4 . It adds methods to create, update, and delete secrets. Along those lines, this PR also adds accessors for secret templates, including a template's password generation function.

This PR is a pre-requisite for [issue 26](https://github.com/thycotic/terraform-provider-tss/issues/26) in [terraform-provider-tss](https://github.com/thycotic/terraform-provider-tss)

2022-01-07 20:11 UTC, amigus requested changes
These changes look great!

The only thing is too much `omitempty`. Please update to only use `omitempty` where appropriate.

After that minor change, we will be happy to take these changes. Thanks!

2022-01-07 20:11 UTC, amigus commented on server/secret.go
> +	FolderID, ID, SiteID                                                       int           `json:",omitempty"`
The Name and IDs shouldn't be `omitempty`. I suggest:
```golang
type Secret struct {
	Name                                                                        string
	FolderID, ID, SiteID, SecretTemplateID, SecretPolicyID                      int
	CheckOutIntervalMinutes, LauncherConnectAsSecretID, PasswordTypeWebScriptID int           `json:",omitempty"`
	Active, CheckedOut, CheckOutEnabled                                         bool          `json:",omitempty"`
	AutoChangeEnabled, CheckOutChangePasswordEnabled, DelayIndexing             bool          `json:",omitempty"`
	EnableInheritPermissions, EnableInheritSecretPolicy, ProxyEnabled           bool          `json:",omitempty"`
	RequiresComment, SessionRecordingEnabled, WebLauncherRequiresIncognitoMode  bool          `json:",omitempty"`
	Fields                                                                      []SecretField `json:"Items,omitempty"`
}
```

2022-01-07 20:11 UTC, amigus commented on server/secret.go
>  type SecretField struct {
Analogously:
```
type SecretField struct {
	ItemID, FieldID, FileAttachmentID     int
	FieldName, Slug                       string
	FieldDescription, Filename, ItemValue string `json:",omitempty"`
	IsFile, IsNotes, IsPassword           bool   `json:",omitempty"`
}
```

2022-01-07 20:11 UTC, amigus commented on server/secret_template.go
> +	Name   string                `json:",omitempty"`
I don't think any of these should be `omitempty`

2022-01-07 20:11 UTC, amigus commented on server/secret_template.go
> +type SecretTemplateField struct {
I suspect most of these shouldn't be either.

2022-01-07 21:10 UTC, chaserb commented on server/secret.go
> +	FolderID, ID, SiteID                                                       int           `json:",omitempty"`
Done. The only one I left in the `omitempty` camp is `SecretPolicyID`. The default value of `0` causes the server to complain about an invalid policy id.

2022-01-07 21:11 UTC, chaserb commented on server/secret.go
>  type SecretField struct {
Done.

2022-01-07 21:11 UTC, chaserb commented on server/secret_template.go
> +	Name   string                `json:",omitempty"`
Removed all the tags.

2022-01-07 21:11 UTC, chaserb commented on server/secret_template.go
> +type SecretTemplateField struct {
Removed all the tags.

2022-01-10 02:33 UTC, chaserb commented
Hello @amigus . All the issues have been resolved. Let me know what you think.

2022-01-10 18:16 UTC, EndlessTrax commented
Hi @chaserb, Thank you so much for this PR. It's a lot of work for which we're very grateful. 

My only question is why use `omitempty` at all? My understanding (please correct me if I'm wrong) is that it will remove the `key` from the JSON string if the value is `0` or `nil`. This means the SDK will return a different payload than the Secret Server API would, which could be potentially confusing, and will need explicit documentation. 

So I guess my question really is, what problem does `omitempty` solve that makes this tradeoff worthwhile?

2022-01-10 20:04 UTC, chaserb commented
Hi @EndlessTrax , It looks like we can get away with `omitempty` altogether with the exception of `SecretPolicyID` and `PasswordTypeWebScriptID`.  You are correct that the `omitempty` removes the item from from JSON if either of those two values are `0`. In the case of these two IDs, however, I'm afraid that is what's required. Leaving a value of `0` for either of these two attributes causes the server to complain about invalid IDs. 

This is what I get for when leaving the `"SecretPolicyID":0` in the request body:

```
2022/01/10 12:57:00 [DEBUG] response body:
    secret_test.go:72: calling secrets.CreateSecret: 400 Bad Request: {
          "errorCode": "API_InvalidSecretPolicy (SecretPolicyId)",
          "message": "API_InvalidSecretPolicy (SecretPolicyId)"
        }
```

This is what I get when I leave `"PasswordTypeWebScriptID":0` in the request body:

```
2022/01/10 12:59:09 [DEBUG] response body:
    secret_test.go:97: calling secrets.UpdateSecret: 400 Bad Request: {
          "errorCode": "API_InvalidPasswordTypeWebScript",
          "message": "The specified password changing script is invalid or inactive."
        }
```

I've tested this both on the hosted `https://my-tenant.secretservercloud.com/` and on our on-premise v11.0 server.

I'll make another commit that pares `omitempty` down to the bare minimum.

2022-01-11 15:30 UTC, EndlessTrax commented
Sounds good to me, thanks @chaserb. Once @amigus approves the changes, I'll merge. 

Thanks again for all your hard work.

2022-01-11 15:35 UTC, amigus approved these changes
Thanks for your contribution and diligence!

2022-01-11 16:47 UTC, merged